- src/components/common/MenuBar.tsx
MenuBar 컴포넌트 작성
```
focusedPosition: 'left' | 'right';
leftText: string;
rightText: string;
path: string;
```
위와 같은 형식의 props를 받아서 사용합니다.
06.02 코드리뷰 바탕으로 props명 수정했습니다.
`href` -> `path`
> [CRES-31] feat: MenuBar 컴포넌트 작성

- src/components/common/Input.tsx
- src/constants/index.ts
- tailwind.config.ts
- close #42 
비제어 컴포넌트로 사용하는 것과 포커스 주는 상황을 고려해서 `forwardRef()`를 사용했습니다.
사이즈는 small, middle, large 3가지로 구분해놓았고 id, label을 필수값으로 넘겨받아서 사용합니다.
옵셔널로 disabled, required, link를 넘겨서 사용하고 필요한 attribute를 넘겨서 사용합니다.
small size
disabled
large size, required
link
인풋이 포커스 되었을 때 임의로 로고색인 보라색으로 스타일링 했습니다!
폼 검증 관련 에러에 대해서도 고민해봤는데 인풋 컴포넌트가 아닌 상위에서 관리하는 게 적합할 거 같아서 일단 제외했습니당
여러가지 상황 고려해서 작성해보았는데 빠진 부분 있으면 의견주세요.ㅎㅎ
> [CRES-52] feat: Input 컴포넌트 추상화 작성

- src/components/common/Header.tsx
- src/components/common/Loader.tsx
- src/pages/_app.tsx
- tailwind.config.ts
- close #52 
- `Suspense` 글로벌 적용
- `LoginModal` lazy import를 통한 코드 스플리팅
- QueryClient defaultOptions `suspense:true` 적용
LoginModal을 `코드스플리팅`한 이유는 다음과 같습니다.
1. 메인페이지의 번들사이즈가 매우 큼
2. 1번의 이유로 로딩 속도가 느림에도 불구하고 구글 로그인에 사용되는 스크립트와 컴포넌트를 초기 로딩 시 한 번에 가져와야함
4. 로그인 상태일때는 로그인 모달이 필요없기 때문에 로그인 모달을 번들파일에 포함 되는 것이 불필요
`Suspense`는 이후 스켈레톤 UI를 적용할 것을 고려해서 글로벌하게 적용하지 않고, 필요한 페이지에서만 비동기를 감지하는 컴포넌트를 Suspense로 감쌀 생각이였습니다. 무분별한 suspense 사용도 사용자 경험에 저해될 수 있을 거 같아요.
하지만 필요한 페이지에서 컴포넌트를 Suspense로 감쌌을 때 fallback UI가 보이질 않아 우선 진입점 파일에 적용하였습니다ㅠ
추후 해결 방법을 찾아보도록 하겠습니다.
> [CRES-57] Suspense, lazy import 적용

- public/svg/clear_button_nobackground.svg
- src/components/common/TagInput.tsx
- close #51 
- 태그 input 컴포넌트 작성
- 태그 추가 및 삭제 구현
- 중복 태그 alert 구현
> 중복 태그임을 알려주는 alert를 토스트 메시지로 알려주는 것은 어떻게 생각하시나요..?
> 아니면 경고 문구를 input 아래쪽에 보여주는게 좋으려나요...? <- 이 경우는 태그 목록이 아래쪽으로 밀려나서 우선 alert로 구현하긴 했습니다!
> [CRES-54] 태그 컴포넌트 추상화 구현

- src/components/common/Header.tsx
- src/components/common/Loader.tsx
- src/components/search/StudyList.tsx
- src/components/skeleton/StudyListSkeleton.tsx
- src/mocks/data/studyList.json
- src/mocks/handlers/studyHandlers.ts
- src/pages/_app.tsx
- src/pages/search/index.tsx
- tailwind.config.ts
- close #61 
- 검색 결과 페이지 Skeleton UI 적용
- Suspense 컴포넌트 별 적용
1. 저번에 fallback UI가 보이지 않았던 이유는 Suspense는 감싼 컴포넌트에서 Proimise 상태를 감지해야 작동하기 때문입니다.
그래서 `StudyList` 컴포넌트로 분리한 후 Suspense로 감쌌습니다.
진입점 파일에 감싸게 되면 모든 컴포넌트가 다 로딩이 되어서야 사용자는 화면을 볼 수 있습니다.  로딩이 지연되는 컴포넌트를 기다리지 않고 나머지 컴포넌트를 먼저 렌더링 할 수 있게 됩니다.
2. 빌드 시 TailwindCSS order warning 문구가 너무 많아서 클래스 네임 순서를 수정했습니다.
> [CRES-61] 검색 결과 페이지 Skeleton UI 적용 및 Suspense 개선

- src/components/common/Layout.tsx
- src/components/detail/StudyDetailContent.tsx
- close #89 
상세페이지 컨텐츠 간격이 지나치게 넓은 현상과, overflow-x: hidden임에도 불구하고 가로 스크롤바 생기는 현상을 수정합니다.
> [CRES-82] 상세페이지 컨텐츠 간격 조정, 가로 스크롤바 생기는 현상 수정

- src/components/common/Header.tsx
- src/hooks/queries/useGetProfile.ts
- src/middleware.ts
- src/pages/_app.tsx
- close #87 
- middleware를 통해 쿠키 여부에 따라 리다이렉션을 적용하였습니다.
- 페이지에 접근하기 전에 미들웨어를 통해 접근 여부를 검사합니다.
- 우선 /mypage와 /study/create 만 적용하였습니다.
_app.tsx에 전역으로 `useIsMounted`를 적용한 이유는 다음과 같습니다.
- 개발 환경에서는 문제없으나 배포 환경에서 빌드 시 에러가 발생합니다.
- /mypage에 접근 시 리다이렉션이 최우선적으로 적용되어야함에도 불구하고 API 콜이 들어갑니다. 유사한 사례는 찾지 못했습니다.
- 401 에러가 발생하고 Axios Interceptor의 토큰 재발급 로직이 실행되면서 서버사이드에서 document.cookie에 접근하기 때문에 에러가 발생합니다.
- 전역에 useIsMounted를 적용해 해결할 수 있었지만 **우려되는 점**은 전역에 useIsMounted을 적용했기 때문에 어떤 사이드 이펙트를 가져올 지 모른다는 점입니다.
- Next.js 특징때문에 어쩔 수 없는 문제로 보이며 토큰이 안 담겨졌을 때 에러코드를 구분할 수 있다면 해결할 수 있을 것 같아요.
개발하시면서 해결 방법 생각나면 공유 부탁드립니다!
> [CRES-71] middleware를 통해 로그인 여부에 따라 페이지 접근 제어 및 리다이렉션 적용

- src/@types/index.d.ts
- src/apis/study/study.d.ts
- src/apis/study/studyApi.ts
- src/components/common/Card.tsx
- src/components/common/Input.tsx
- src/components/common/SelectBox.tsx
- src/components/search/StudyList.tsx
- src/constants/search.ts
- src/hooks/queries/useGetStudy.ts
- src/hooks/useStudyList.ts
- src/mocks/handlers/studyHandlers.ts
- src/pages/index.tsx
- src/pages/search/index.tsx
- close #93 
- close #92 
- 메인페이지 검색 기능 구현
- 태그 입력 시 태그 쿼리 파라미터만, 일반 문자열 입력 시 `post_title`, `study_name` 쿼리 파라미터가 동시에 적용됩니다.
- 검색 페이지 필터링 기능 구현
양이 좀 많아서 비즈니스 로직 위주로 확인해주시면 될 것 같습니다 ..
- 메인페이지 & 검색페이지 모두 검색 문자열을 입력하지 않았다면 검색 페이지로 이동하거나 쿼리값을 모두 제거하는 방향으로 구현해놓았습니다.
- ordering, is_closed 쿼리 파라미터를 적용 안 했을 경우 기본값으로 각각 최신순 / 모집중 + 모집완료로 응답이 오는데, 오른쪽의 SelectBox 기본값은 모집중이므로 모순이 있어서 의논해봐야할 것 같습니다.
이 부분에 대해서 의견 있으시면 주세요.
버그가 발생하거나 개선해야 할 부분 의견 주시면 감사하겠습니다. 잘 부탁드립니다!
> [CRES-83] 스터디 그룹 목록 검색 및 필터링 기능 구현

- src/components/form/StudyForm.tsx
- src/pages/study/detail/edit/[id].tsx
- close #107 
- 아래 두 가지 경우에 대해 접근한 스터디 id에 맞는 상세 페이지로 이동합니다.<br>(ex. `/study/detail/edit/1` -> `/study/detail/1`)
* 로그인한 사용자의 uuid와 스터디 leaders 첫번째 사용자의 uuid가 다른 경우
* 스터디의 `is_closed`가 true인 경우
토스트 메시지가 꼭 필요한 상황은 아닌것 같아서 지우는 게 나을까요?
> [CRES-93] 작성자가 아닌 경우 및 모집이 마감된 경우 페이지 접근 제한

- src/components/home/HomeStudyList.tsx
- src/components/search/StudyList.tsx
- src/components/skeleton/StudyListSkeleton.tsx
- src/hooks/mutations/usePutUser.ts
- src/hooks/queries/useGetStudy.ts
- src/pages/index.tsx
- src/pages/login/index.tsx
- src/pages/search/index.tsx
- close #112 
- 메인페이지 랜덤 스터디 목록 구현
- 검색 결과의 StudyList가 중앙 정렬되어 있지 않은 문제를 해결하고 레이아웃과 디자인 조정
- 로그인 페이지의 PageLayout 제거
- usePutUser onSuccess 콜백 함수의 누락된 토스트 메시지 추가
임시로 일단 메인페이지의 랜덤스터디 적용해놓았는데 디자인과 API 스펙 사이에 애매한 부분이 있어서 스크롤 방식으로 적용할건지 딱 4개만 보여주는건지 의논해봐야될 것 같습니당
> [CRES-89] 메인페이지 랜덤 스터디 목록 구현

- src/apis/study/studyApi.ts
- src/components/manage/MyStudyList.tsx
- src/components/manage/OpenStudyCard.tsx
- src/components/skeleton/MyStudyListSkeleton.tsx
- src/constants/index.ts
- src/hooks/mutations/useDeleteStudy.ts
- src/hooks/queries/useGetStudy.ts
- src/middleware.ts
- src/pages/study/manage/index.tsx
- close #111 
- 무한 스크롤
- 스켈레톤 로딩
- 스터디 삭제
- 스터디 기간, 모집 기간 표시
기존 페이지가 `/study/manage`에 구현되어 있어서 api 폴더 및 라우팅을 모두 `/study` 로 통일했는데, api 경로는 `{BASE_URL}/auth/...` 여서 api는 `/user`에 작성해야할지 고민입니다...
기간 관련 부분은 api 수정이 되는대로 업데이트 하겠습니다! 
<table>
<tr>
<td>스터디 O</td>
<td>스터디 X</td>
</tr>
<tr>
<td><img width="1065" alt="스터디 있을 때" src="https://github.com/crescenders/crescendo-frontend/assets/51291185/0a00d0e5-e15e-4cdf-b5ac-2f4748166a8f"></td>
<td><img width="1065" alt="스터디 없을 때" src="https://github.com/crescenders/crescendo-frontend/assets/51291185/aff1edd4-7f47-4998-b795-66be54f33ae9"></td>
</tr>
</table>
> [CRES-91] 내가 맡은 스터디 페이지 구현

- src/components/search/NotFoundStudyList.tsx
- src/components/search/StudyList.tsx
- close #119 
- 이전 페이지로 돌아갔을 때 isFetching은 true이나 isFetchingNextPage는 false입니다.
- isFetching -> isFetchingNextPage로 수정하여 해당 문제를 해결했습니다.
> [CRES-97] 검색 결과 페이지에서 뒤로가기를 했을 때 스켈레톤 UI가 뜨는 현상을 해결한다.

- src/apis/study/studyApi.ts
- src/components/common/Toast.tsx
- src/components/detail/ApplyBottomSheet.tsx
- src/hooks/mutations/useApplyStudy.ts
- src/pages/_app.tsx
- close #117 
- 스터디 참여 신청 api 적용
- 신청 바텀 시트 z-index가 토스트 메시지보다 높아 토스트 메시지의 z-index를 수정했습니다.
- 빈 값 입력, 중복 신청
- 신청 성공
> [CRES-94] 스터디 참여 신청 api 연동

- src/apis/tag/tag.d.ts
- src/apis/tag/tagApi.ts
- src/components/home/Banner.tsx
- src/hooks/queries/useGetTags.ts
- close #145 
@TGoddessana 적용을 해보니 어떤 태그는 현재 게시물 목록에 포함되어있는 태그도 있지만 이전에 삭제된 게시물에 포함되어있는 태그도 있고 처음보는 태그도 있더라구요. 혹시 태그가 생성되는 기준이 임의의 태그를 생성해서 저장해두는 방법과 이전에 작성된 게시물의 태그 히스토리를 기준으로 하는걸까요~?
> [CRES-111] 배너에 보여주는 랜덤 태그 구현

- .github/workflows/frontend-ci.yml
- cypress.config.js
- cypress/e2e/login.cy.ts
- cypress/e2e/mobile.cy.ts
- cypress/e2e/search.cy.ts
- package.json
- #207
- 핵심 기능에 대해서 테스트를 작성하였습니다.
- 컴포넌트 테스트는 RTL로 하기 때문에 웹팩 설정을 제거하였습니다.
- cypress-io/github-action@v2 -> v6 최신방식으로 변경 및 `yarn test:e2e` 스크립트 제거
`cypress:open`, `cypress:run`의 실행 결과가 다른데 원인을 모르겠네요 ㅠㅠ 그래서 소극적으로 작성하였습니다ㅠ
cypress 테스트 소요시간이 jest에 비해 10배 이상 길어서 핵심적인 기능만 테스트 하는 것이 좋아보입니다.
- Yarn Berry를 사용하는 프로젝트는 github actions에서 cypress 모듈을 찾을 수 없습니다. `command-prefix: yarn dlx` 를 추가하여 해결하였습니다. https://github.com/cypress-io/github-action/issues/430
- 저희 프로젝트는 nginx, docker를 사용하고 있지 않아 github actions에서 별도의 서버가 없기 때문에 api 호출이 포함되어야만 하는 테스트는 통과하지 못합니다. 따라서 관련된 테스트를 모두 제거하였습니다. 추후에 테스트 작성하시게 되면 해당사항 유의하시면 될 것 같습니다
> [CRES-139] 사용자 시나리오에 따른 E2E 테스트 작성

- public/robots.txt
- src/components/common/TextArea.tsx
- src/components/detail/ApplyBottomSheet.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/detail/SubmissionDetailContent.tsx
- src/components/home/Banner.tsx
- src/components/submission/SubmissionList.tsx
- src/hooks/queries/useGetAssignment.ts
- src/hooks/queries/useGetStudy.ts
- src/hooks/queries/useGetSubmission.ts
- src/hooks/queries/useGetTags.ts
- src/pages/index.tsx
- src/pages/study/assignment/detail/[...id].tsx
- src/pages/study/assignment/submission/detail/[...id].tsx
- src/pages/study/detail/[id].tsx
- close #228 
- 메인 페이지, 상세 페이지 클라이언트 -> 서버 사이드 렌더링 적용
- 메인 페이지와 검색 페이지도 색인화를 허용하도록 robots.txt 파일 수정
- 과제 관련 페이지의 Layout Shift 현상 해결을 위한 Suspense 재적용
메인 페이지에서는 두 개의 API를 요청합니다.
``` ts
await queryClient.prefetch(['tags'])
await queryClient.prefetch(['random'])
```
의 형태로 요청하지만 tags의 API 요청 수행이 끝난 후에 random API를 요청하기 때문에 waterfall 현상이 발생합니다.
따라서, 병렬적으로 API를 요청하기 위해 `Promise.all()`를 사용하였습니다.
``` ts
await Promise.all([
queryClient.prefetchQuery(['tags']),
queryClient.prefetchQuery(['random'])
])
```
하지만 여전히 문제는 발생하였습니다.
랜덤 API의 리소스가 태그 API보다 크기 때문에 랜덤 API만 서버 사이드에서 렌더링하도록 적용하였고, 태그 API는 이후 클라이언트 사이드에서 렌더링을 거치는 방식으로 적용하였습니다.
결론적으로 메인 페이지의 초기 렌더링 속도를 2.97s -> 1.8s (1.1s 감소)로 개선할 수 있었습니다.
> 검색 엔진 최적화 및 초기 렌더링 속도 향상을 위한 SSR 적용

- src/components/common/AuthLayout.tsx
- src/components/common/Header.tsx
- src/components/common/NavigateList.tsx
- src/components/common/SelectBox.tsx
- src/components/home/Banner.tsx
- src/hooks/useClickAway.ts
- src/pages/login/index.tsx
- close #243 
- 모바일 환경에서 헤더의 네비게이션 바를 끌 수 있도록 useClickAway 훅을 통해 개선하였습니다.
- 배너의 태그 목록의 길이가 영역을 초과할 경우 스크롤을 할 수 있도록 적용하였습니다.
- 로그인 페이지의 반응형 디자인을 적용하였습니다.
https://github.com/crescenders/crescendo-frontend/assets/48711263/42932cf2-96f1-4180-8802-3c0a6baf7871
> UI 개선사항 적용

- src/components/manage/MyStudyList.tsx
- src/pages/mypage/manage.tsx
- src/pages/study/detail/edit/[id].tsx
- close #253
- 스터디 수정 페이지에서 새로고침시 발생했던 오류 해결
- useEffect 훅 내부에서 study가 있는지 추가적으로 확인
- 새로고침시 초반에 한 번 스터디 id가 undefined인 상태로 요청이 보내졌던 현상 해결
> 해결은 어찌저찌 됐지만... 애초에 스터디 작성 폼 설계를 잘못한 것 같아서 슬푸네여 허허 ㅠㅠㅠㅠ 아예 getServerSideProps로 스터디 상세 정보를 받아오는 방법도 생각해봤는데 좀 불필요하게 사용하는 것 같아서 틀었습니다...
> 스터디 수정 페이지 오류 해결

- src/components/common/Header.tsx
- close #256 
- 새로고침 시 순간적으로 로그인/회원가입 문구가 뜨는 현상이 발생합니다.
- 서버에서는 `<RecoilRoot/>`에 접근하지 못하기 때문에 Header 컴포넌트를 로그인/회원가입으로 생성합니다.
- 렌더링 시점을 페이지가 전환되는 시점이 아닌 useIsMounted를 적용하여 마운트 시 렌더링되도록 해결하였습니다.
> 서버에서 정적생성된 페이지와 불일치하는 현상 해결

- src/components/search/StudyList.tsx
- src/hooks/queries/useGetStudy.ts
- src/pages/search/index.tsx
- close #276
- 검색 필터링을 적용할 때 새로 페칭하는 것이 아닌 내부에서 캐싱된 값을 찾습니다. 따라서, `isFetching`의 값이 `false`이기 때문에 스켈레톤 UI가 보이지 않는 문제가 발생했습니다. 따라서, useGetStudy의 `staleTime: 0`으로 설정하고 한 번 검색했던 조건으로 재검색 할 경우 fetching 하는 동안 이전의 데이터를 보여주기 때문에 `gcTime` 또한 0으로 설정하였습니다.
- 검색 필터링이 초기화 될 때 마감여부 셀렉트 박스가 초기화 되지 않았습니다. 누락된 해당 부분을 추가했습니다.
> 검색 필터링을 변경할 때 로딩 UI가 보이지 않는 문제 수정

- src/pages/_app.tsx
- close #279 
SSR 과정을 거치고 클라이언트에서 재페칭하는 것을 방지하기 위해 staleTime의 기본값을 60초로 설정하였습니다.
하지만 이전 이슈를 수정하는 과정에서 너무 과하게 설정되어 있는 느낌을 받았고 [TanStack GitHub Repo](https://github.com/TanStack/query/blob/main/examples/react/nextjs-suspense-streaming/src/app/providers.tsx)에서 또한 5초로 Best Practice를 채택하고 있기 때문에 5초로 수정합니다.
> staleTime 디폴트 옵션 조정
