- src/components/common/Button.tsx
- tailwind.config.ts
Button 컴포넌트 작성
- close #4
- width, height, font-size 속성을 props로 전달해서 사용합니다.
- box-shadow 속성을 tailwind의 shadow-[ ] 로 임의의 값을 전달할 수 없어서 tailwind.config.ts에 속성값을 추가했습니다.
- ShadowButton, NormalButton(취소, 삭제)으로 분리했습니다.
- ShadowButton : width, height, onClick 값을 전달합니다.
- NormalButton : text, onClick, isNormal 값을 전달합니다.
``` javascript
<div className="flex flex-col items-center gap-y-2">
<Button text="과제 등록하기" className="h-9 w-[140px]" />
<Button text="취소" isNormal={true} />
<Button text="삭제" isNormal={true} />
</div>
```
> [CRES-27] feat: Button 컴포넌트 작성

- src/components/common/Header.tsx
- resolve #10
- 상위 요소에 버블링이 전파되지 않도록 각 요소에 `event.stopPropagation()`을 할당했습니다.
- isHover -> isOpen 으로 네이밍 변경했습니다.
> [CRES-30] fix: onMouse 이벤트 리렌더링 현상 해결

- src/components/common/Header.tsx
- src/components/common/NavigateList.tsx
- tailwind.config.ts
- close #12 
- 드롭박스 정보수정 항목 추가했습니다
- 헤더에 shadow 속성과 hover 시 텍스트 색상이 변화 디자인이 누락되어 있어서 추가했습니다.
https://github.com/crescenders/crescendo-frontend/assets/48711263/1d669cc7-c83d-419a-b82f-9823fc4ffd24
> [CRES-33] refactor: 드롭박스 디자인 수정사항 반영

- src/pages/study/apply/index.tsx
더미 데이터를 이용해서 신청한 스터디 페이지 퍼블리싱했습니다.
- /study/apply 로 url 설계했습니다.
- 더미데이터를 사용했습니다.
- 브라우저의 `width`가 줄어들 때 스터디 카드가 깨지지 않도록 `flex-wrap`을 사용했습니다.
| <img src="https://github.com/crescenders/crescendo-frontend/assets/87893624/bca77024-8a46-4ba2-a428-1ef47da7d6f9"> | <img src="https://github.com/crescenders/crescendo-frontend/assets/87893624/62181cc8-c7bc-4323-9858-49feb3132878"> |<img src="https://github.com/crescenders/crescendo-frontend/assets/87893624/81cfbaca-12c2-464e-aa7d-ce86b6f8fb71">|<img src="https://github.com/crescenders/crescendo-frontend/assets/87893624/c59c4301-0321-4fdb-8ee1-1004337f4be2">|
|--|--|--|--|
> [CRES-40] feat: 신청한 스터디 페이지 퍼블리싱

- src/apis/study/study.d.ts
- src/apis/study/studyApi.ts
- src/components/common/Card.tsx
- src/components/common/SelectBox.tsx
- src/hooks/query/useGetStudy.ts
- src/hooks/useIntersection.ts
- src/hooks/useIsMounted.ts
- src/hooks/useIsWorker.ts
- src/hooks/useModal.ts
- src/mocks/browser.ts
- src/mocks/data/studyList.json
- src/mocks/handlers/studyHandlers.ts
- src/mocks/server.ts
- src/pages/index.tsx
- src/pages/search/index.tsx
- close #48 
- `useIntersection` 커스텀 훅 구현 
- `useGetStudy` 훅 작성 (useInfiniteQuery 사용)
- 홈 화면 무한 스크롤 구현
- 검색어로 스터디 목록을 가져오는 MSW handler 작성
- 커스텀 훅 JSDoc 작성
Card 컴포넌트가 매우 복잡해서 간소화가 필요하다고 느껴집니다. 이 전 리뷰에서 `big / small, middle` 두 가지로 분리할 수 있을 거 같다고 리뷰한 적이 있는데, 더 좋은 방법이 있을지 고민해봐야 될 거 같아요.
> [CRES-55] 무한 스크롤 기능 구현

- src/apis/auth/auth.d.ts
- src/apis/auth/authApi.ts
- src/apis/instance.ts
- src/apis/user/userApi.ts
- src/components/modal/LoginModal.tsx
- src/utils/token.ts
> [CRES-60] API 수정사항 반영 

- src/constants/validation.ts
- src/pages/study/create/index.tsx
- src/utils/validate.ts
- close #72 
- 스터디 상세 소개 중, 코드 블록으로 감싸져 있지 않은 `<script> ... </script>` 및 `<script ... />` 태그 작성 제한
- 상세 소개를 작성했다 지웠을 경우 값이 `<p><br></p>`으로 남아있어 빈 항목으로 취급되지 않던 현상 수정
<table>
<tr>
<td><img width="559" alt="스크린샷 2023-09-08 오후 7 08 38" src="https://github.com/crescenders/crescendo-frontend/assets/51291185/2a0d272b-3060-49e9-9db0-0c1d69333f8d"></td>
<td><img width="560" alt="스크린샷 2023-09-08 오후 7 08 55" src="https://github.com/crescenders/crescendo-frontend/assets/51291185/074a663b-c8c9-4a88-8c57-79ccfdfdf72f"></td>
</tr>
</table>
> [CRES-76] feat: 스터디 상세 소개에 script 태그 제한

- src/apis/category/category.d.ts
- src/apis/category/categoryApi.ts
- src/apis/study/study.d.ts
- src/apis/study/studyApi.ts
- src/components/common/Slider.tsx
- src/hooks/mutations/useCreateStudy.ts
- src/hooks/queries/useGetCategories.ts
- src/hooks/queries/useGetProfile.ts
- src/hooks/useStudyForm.ts
- src/mocks/handlers/studyHandlers.ts
- src/pages/study/create/index.tsx
- close #73 
- 스터디 개설 API 연동
- 카테고리 상수 -> 카테고리 조회 API 사용 변경
- 글 등록 API 로딩 중, 로딩 화면 표시
- 모집 인원 슬라이더 최솟값 1 -> 2로 변경
- 날짜 yyyy-mm-dd 형식으로 변경
> 현재 이미지 전송시 payload에는 값이 확인되지만, 실제 개설된 스터디에는 랜덤 이미지가 보여집니다.
> 이 점은 조금 더 확인 후 수정하겠습니다...
> [CRES-75] feat: 스터디 개설 API 연동

- src/pages/study/create/index.tsx
- close #80 
- 카테고리 조회 api -> 카테고리 상수 변경
> [CRES-78] 카테고리 상수를 사용하는 기존 방식으로 변경

- src/apis/instance.ts
- src/components/common/NavigateList.tsx
- src/components/modal/LoginModal.tsx
- src/hooks/mutations/useDeleteUser.ts
- src/hooks/useUser.ts
- src/utils/cookie.ts
- src/utils/token.ts
- close #85 
- refreshToken 쿠키로 저장 위치 변경
- 쿠키 저장, 가져오기, 삭제 유틸함수 생성
> [CRES-79] refreshToken 저장 위치 쿠키로 변경

- src/apis/study/studyApi.ts
- src/components/common/Calendar.tsx
- src/components/common/SelectDateBox.tsx
- src/components/common/Slider.tsx
- src/components/common/TagInput.tsx
- src/components/common/UploadImage.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/form/StudyForm.tsx
- src/hooks/mutations/useDeleteStudy.ts
- src/hooks/mutations/useEditStudy.ts
- src/hooks/queries/useGetStudy.ts
- src/hooks/useStudyForm.ts
- src/pages/study/create/index.tsx
- src/pages/study/detail/edit/[id].tsx
- close #82 
- 스터디 폼을 컴포넌트로 분리
- 스터디 수정 및 삭제 api 작성, 적용
- 스터디 수정시 폼에 기존 내용 표시
> [CRES-80] 스터디 수정, 삭제 API 연동

- src/apis/study/study.d.ts
- src/components/common/Card.tsx
- src/components/common/Header.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/modal/LoginModal.tsx
- src/components/search/StudyList.tsx
- src/hooks/queries/useGetStudy.ts
- src/hooks/useUser.ts
- src/pages/index.tsx
- src/recoil/auth.ts
- close #97 
- 스터디 개설자가 본인일 경우에만 수정/삭제 버튼 노출 
- 마감된 스터디일 경우 수정 금지
- `useGetStudyGroupList` 훅의 pageParam을 undefined로 초기화하도록 수정
> [CRES-84] 스터디 개설자의 본인 여부를 판단해 수정/삭제 버튼을 노출하고 마감된 스터디일시 수정을 금지한다.

- src/components/skeleton/StudyDetailSkeleton.tsx
- src/pages/study/detail/[id].tsx
- tailwind.config.ts
> [CRES-86] 스터디 상세페이지 스켈레톤 UI 구현

- src/components/common/TagInput.tsx
- src/components/form/StudyForm.tsx
- src/constants/validation.ts
- src/hooks/useStudyForm.ts
- src/utils/validate.ts
- close #95 
- 태그 유효성 검사 추가 (1~20자, 공백 제외)
- 이미지 유지, 삭제, 변경을 판단하는 조건 변경
> [CRES-85] 스터디 수정 페이지 개선

- src/apis/study/study.d.ts
- src/components/detail/StudyDetailContent.tsx
- close #123 
상세페이지의 리더 이메일 정보를 추가하고 _links 응답 데이터 타입을 삭제하였습니다.
> [CRES-99] 스터디 상세페이지 리더 이메일 정보 추가

- src/components/search/StudyList.tsx
- src/hooks/useStudyList.ts
- src/pages/search/index.tsx
> [CRES-102] 검색 페이지의 라우팅 쿼리값의 오타를 수정한다.

- src/pages/404.tsx
- tailwind.config.ts
> [CRES-106] 404 페이지 구현

- postcss.config.js
- src/pages/mypage/manage/index.tsx
- src/pages/study/detail/member/[id].tsx
- close #133 
- 내가 맡은 스터디 레이아웃 조정
- 멤버 보기 페이지 카드 간격 조정
- y gap 추가
- flex-wrap 추가
> ➕ 작업 중 CSS nesting 관련 경고가 떠서 플러그인에 추가했습니다.
> [CRES-107] 내가 맡은 스터디, 멤버 보기 페이지 반응형 디자인

- src/components/common/Header.tsx
- src/components/common/HomeLayout.tsx
- src/components/common/PageLayout.tsx
- src/components/home/Banner.tsx
- src/components/home/RandomStudyList.tsx
- src/pages/index.tsx
- close #139
- 메인페이지 배너 컴포넌트로 분리
- `Header`, `Banner` width: 100%을 차지하도록 수정
잘 수정한 게 맞을까요..? 검토 부탁드립니다 선생님
> [CRES-105] 헤더 및 배너 전체 가로길이 차지하도록 레이아웃 조정

- src/components/detail/ApplyBottomSheet.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/search/StudyList.tsx
- src/pages/search/index.tsx
- close #149 
과제 상세페이지와 검색 페이지를 반응형에 대응할 수 있도록 디자인하였습니다.
> [CRES-113] 과제 상세페이지, 검색 페이지 반응형 디자인

- src/apis/instance.ts
- close #141 
리프레쉬 토큰을 교체하지 않았기 때문에 발생한 문제입니다.
> [CRES-112] 토큰 재발급 과정에서 블랙리스트 응답오는 현상 해결

- src/components/common/ProgressBar.tsx
- src/pages/study/assignment/[id].tsx
- src/utils/getProgress.ts
> [CRES-114] 스터디 진행도가 100% 이상인 경우 그 이상 초과되는 것을 수정한다.

- src/apis/submission/submission.d.ts
- src/apis/submission/submissionApi.ts
- src/components/manage/AssignmentCard.tsx
- src/components/skeleton/SubmissionListSkeleton.tsx
- src/components/submission/SubmissionList.tsx
- src/hooks/queries/useGetSubmission.ts
- src/pages/study/assignment/submission/[...id].tsx
- close #152 
- 제출된 과제 목록 api 작성
- 페이지 작성
- 기존 `AssignmentCard` 컴포넌트에 작성한 페이지 연결
> 과제를 제출하려면 다른 사람들이 제출한 과제를 다 봐야 한다는 게 초큼 거시기 한 것 같아서 "과제 제출하기" 버튼을 화면 하단에 고정시켰는데 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.. 다른 페이지와 동일하게 고정된 위치가 아닌 목록 하단에 두는 게 나을까요?
> [CRES-109] 제출된 과제 목록 페이지 구현

- src/apis/submission/submissionApi.ts
- src/components/detail/SubmissionDetailContent.tsx
- src/components/submission/SubmissionList.tsx
- src/hooks/mutations/useDeleteSubmission.ts
- src/hooks/mutations/useEditSubmission.ts
- src/hooks/queries/useGetSubmission.ts
- src/pages/study/assignment/submission/detail/[...id].tsx
- src/pages/study/assignment/submission/edit/[...id].tsx
- close #164 
- 제출한 과제 상세 페이지 구현
- 제출한 과제 수정/삭제 기능 구현
> 부분 수정의 경우
> ----
> 현재 제목은 patch로 수정이 가능하지만 내용은 불가해서, 이따 낮에 재균이에게 의도한 부분인지 물어보고 추가적으로 수정하겠습니다. 
<table>
<tr>
<td>상세 페이지</td>
<td>수정 페이지</td>
</tr>
<tr>
<td><img src="https://github.com/crescenders/crescendo-frontend/assets/51291185/25e417ba-c1c9-41b1-97c7-2e5425d89d55" /></td>
<td><img src="https://github.com/crescenders/crescendo-frontend/assets/51291185/758958eb-1dd8-46f1-a391-f6ddb0220c0e" /></td>
</tr>
</table>
> [CRES-117] 제출된 과제 상세 페이지 구현

- src/components/common/SelectDateBox.tsx
- src/components/common/TagInput.tsx
- close #168 
- 날짜 선택 박스 텍스트 크기 축소 (13px -> 12px)
- 태그 입력 박스 요소 간 간격 추가 (에러 메시지 및 입력한 태그)
<table>
<tr>
<td>입력한 태그</td>
<td>에러 메시지 + 입력한 태그</td>
</tr>
<tr>
<td><img src="https://github.com/crescenders/crescendo-frontend/assets/51291185/05dcfd56-0ec4-485b-bea4-04054c5a885d" /></td>
<td><img src="https://github.com/crescenders/crescendo-frontend/assets/51291185/b305333e-fad9-475f-b4ef-1a66830f4945" /></td>
</tr>
</table>
> [CRES-118] 스터디 개설 페이지 개선

- src/apis/application/applicationApi.ts
- src/apis/assignment/assignmentApi.ts
- src/apis/auth/authApi.ts
- src/apis/category/categoryApi.ts
- src/apis/instance.ts
- src/apis/member/memberApi.ts
- src/apis/study/studyApi.ts
- src/apis/submission/submissionApi.ts
- src/apis/tag/tagApi.ts
- src/apis/user/userApi.ts
- close #172 
배경은 #172 를 확인해주세요.
- Axios 인스턴스를 두 가지 타입으로 분리하여 해결하였습니다. 죄송합니다
> [CRES-123] 토큰 재발급 이슈 해결

- src/apis/assignment/assignmentApi.ts
- src/components/assignment/AssignmentList.tsx
- src/components/common/MenuBar.tsx
- src/components/skeleton/AssignmentListSkeleton.tsx
- src/components/skeleton/StudyListSkeleton.tsx
- src/hooks/queries/useGetAssignment.ts
- src/pages/study/assignment/[id].tsx
- src/pages/study/assignment/detail/[...id].tsx
- close #178 
- 무한 스크롤 적용
- Suspense, Error Boundary 적용
- 메뉴 상단 마진값 통일
> [CRES-125] 과제 보기 페이지 리펙토링

- src/components/detail/AssignmentDetailContent.tsx
> [CRES-127] 과제 작성일 표기 오류 수정

- __tests__/utils/cookie.test.ts
- __tests__/utils/formatUTC.test.ts
- __tests__/utils/getDevice.test.ts
- __tests__/utils/getErrorMessage.test.ts
- __tests__/utils/getProgress.test.ts
- __tests__/utils/validate.test.ts
- close #186 
제가 작성했던 유틸함수들의 테스트 코드를 작성하였습니다.
> [CRES-129] 유틸함수 테스트 코드 작성

- __tests__/hooks/useIsMounted.test.ts
- __tests__/hooks/useModal.test.ts
- __tests__/hooks/useScript.test.tsx
- src/hooks/useScript.ts
> [CRES-130] Custom hook 테스트 코드 작성

- __tests__/components/common/DropBox.test.tsx
- src/components/assignment/AssignmentList.tsx
> [CRES-136] 진행도와 퍼센트 문구의 간격을 조정한다.

- src/pages/sitemap.xml.tsx
- close #205 
- 사이트맵의 날짜 형식 변경
> [CRES-137] 사이트맵 날짜 형식 변경

- package.json
- yarn.lock
> [CRES-200] Package.json 수정

- src/@types/index.d.ts
- src/components/detail/SubmissionDetailContent.tsx
- src/hooks/mutations/usePostApplication.ts
- src/hooks/mutations/usePostSubmission.ts
- close #202 
- 제출된 과제 상세 너비가 화면 전체를 차지하되 최대 640px까지 가능하게 변경
- useMutation 에러 메시지에 api 응답으로 오는 문자열을 사용하도록 변경
> [CRES-132] 과제 제출 가능 기간 검증 및 디자인 개선

- src/components/manage/OpenStudyCard.tsx
> 인원 항목 크기가 줄어드는 현상 해결

- src/components/common/Card.tsx
- src/components/detail/ApplyBottomSheet.tsx
- src/components/detail/StudyDetailContent.tsx
- src/pages/study/detail/[id].tsx
> 상세페이지에 진입시 스켈레톤 UI가 보이지 않는 현상 해결

- src/components/home/Banner.tsx
- close #224 
태그 데이터가 다른 컨텐츠에 비해 늦게 로드됨에 따라 컨텐츠가 밀려나는 현상을 해결합니다.
> Layout Shift 방지를 위한 height 지정

- src/components/common/Footer.tsx
- src/components/common/HomeLayout.tsx
- src/components/home/RandomStudyList.tsx
> 메인페이지 디자인 수정

- src/components/common/HomeLayout.tsx
- src/components/common/Layout.tsx
> 모바일에서 좌우로 스크롤 되는 현상 수정

- __tests__/utils/getDevice.test.ts
- src/components/common/Header.tsx
- src/components/common/NavigateList.tsx
- src/components/common/SelectBox.tsx
- src/components/detail/ApplyBottomSheet.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/home/Banner.tsx
- src/constants/index.ts
- src/pages/search/index.tsx
- src/utils/getDevice.ts
- tsconfig.json
-  close #237 
이제부터 대부분의 페이지에서 모바일 디바이스 환경에서 어느정도 대처가 가능합니다.
> 모바일 환경에 대응할 수 있도록 디자인을 개선한다.

- src/components/detail/AssignmentDetailContent.tsx
- close #247 
useSuspenseQuery로 변경하여 해결하였습니다.
> 과제 상세페이지가 로딩 되기 전 정적 생성된 페이지가 보이는 현상 수정 

- src/components/common/UploadImage.tsx
> 스터디 개설 페이지의 이미지 제거 버튼 텍스트가 안 보이는 문제를 해결한다. 

- __tests__/components/common/Header.test.tsx
- src/components/common/Header.tsx
- close #263 
모바일 환경에서 로그인 모달의 디자인 대응이 어려웠습니다.
따라서, 모달이 아닌 /login 페이지로 연결되도록 변경하였습니다.
> 모바일 환경일 경우 로그인 페이지로 이동하도록 개선

- src/components/assignment/AssignmentList.tsx
- src/components/common/MenuBar.tsx
- src/components/common/PageLayout.tsx
- src/components/detail/ApplyBottomSheet.tsx
- src/components/detail/AssignmentDetailContent.tsx
- src/components/detail/StudyDetailContent.tsx
- src/components/detail/SubmissionDetailContent.tsx
- src/components/manage/AssignmentCard.tsx
- src/components/skeleton/AssignmentListSkeleton.tsx
- src/pages/mypage/apply.tsx
- src/pages/mypage/status.tsx
- src/pages/study/assignment/[id].tsx
- src/pages/study/assignment/detail/[...id].tsx
- src/pages/study/assignment/submission/[...id].tsx
- src/pages/study/assignment/submission/detail/[...id].tsx
- src/pages/study/detail/[id].tsx
- src/pages/study/member/[id].tsx
- close #261 
- 작성자 본인일 경우 신청하기 버튼 숨기도록 수정하였습니다.
- 상세페이지 이미지 크기가 깨지지 않도록 원본 비율을 유지하도록 변경하였습니다.
- 메뉴바 폰트 사이즈를 반응형으로 적용하고 좌우 여백을 추가하였습니다.
> 작성자 본인일 경우 신청하기 버튼을 숨긴다.

- .github/workflows/frontend-cd.yml
- src/components/common/Header.tsx
> 컨플릭트 해결 후 main 병합

- src/components/common/Header.tsx
> 로그인 관련 액션 분기처리 문자열 수정

- src/components/common/Header.tsx
> 버그 수정 후 재병합

- src/utils/getProgress.ts
- close #281 
iOS 환경에서 Date 객체가 `yyyy-mm-dd` 방식을 인식하지 못해 `yyyy/mm/dd` 포맷으로 치환하여 해결했습니다.
> iOS 환경에서 진행도가 NaN으로 보이는 문제 해결

- .github/workflows/frontend-ci.yml
> 의존성 캐싱 문제 수정
